# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install requests
        pip install json
        
        
    - name: run App
      run: |
        python main.py
        
    - name: Commits
      run: |
        git config --global user.email "18tomcat@gmail.com"
        git config --global user.name "jaehoon-sim"
        git add .
        git commit -m "Auto - Update data with Scraping"
    - name: Push
      run: |
        git push -u origin master
